# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test and Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      working-directory: ./app
      run: yarn install

    - name: Build
      working-directory: ./app
      run: yarn build

    - name: Deploy
      working-directory: ..
      run: bash deploy.sh