name: Build, Test(TODO) and Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted


    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      working-directory: ./app
      run: yarn install

    - name: Build
      working-directory: ./app
      run: yarn build

    - name: Deploy
      working-directory: ..
      run: bash deploy.sh
